### ISSUE TITLE
outlook-encrypt-attachments sample did not work on Outlook Windows Client

### ISSUE THREAD

**Issue by aafvstam** [OfficeDev/Office-Add-in-samples#222]
**URL of sample**

[outlook-encrypt-attachments](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/outlook-encrypt-attachments)

**Describe the bug**

The Add-in seems not to be working in the Office Outlook Windows Client. Tested it successfully on the Web version but the Windows client opened with an error on top of the New Message window.

**To Reproduce**

1. Sideload the Add-in cfm instructions.
2.  Open New Message
3. See error message on top 👇🏻:

**Expected behavior**

Expecting it to run just like the Outlook Web Client

**Screenshots**

![image](https://user-images.githubusercontent.com/5305682/143496680-1d61d5f0-0632-4edf-9a91-faadd89affc8.png)

**Environment**
- Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: 
![image](https://user-images.githubusercontent.com/5305682/143496793-3c795614-5f9f-46fe-a0da-fc9eb93eca32.png)

- Operating System:
![image](https://user-images.githubusercontent.com/5305682/143496855-8d47c11a-f486-4324-8808-fa27258f4260.png)

- Browser (if using Office Online): N/A

**Additional context**

For a repro you can see it in my "Soft as in Software" Live Stream on YouTube:
https://youtu.be/AhvNMzDwoow

**Comment by davidchesnut** [comment]
Hi @aafvstam,

Thanks for noticing this. I renamed the repo to Office-Add-in-samples. But I forgot that this will break all the GitHub pages that host files for the samples. I checked in an update for all samples that fixes this. So it should work for you now.

BTW: Keep in mind that the sample will not encrypt attachments on Outlook on Windows (noted in readme) because it cannot import the crypto library. Only commands.js is loaded when running on Outlook on Windows.

Thanks!
David
