### ISSUE TITLE
Outlook Web SSO Enabled JS Addin

### ISSUE THREAD

**Issue by saaniaki** [OfficeDev/Office-Add-in-samples#224]
Hello,

I have followed [this tutorial to create an SSO-enabled add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs), and I have modified it to be able to use it as an Outlook Web add-in. My problem is that the call to exchange the identity token obtained from Office object available in the browser with a valid MS Graph token is failing with the following error:

```
{
  error: 'invalid_grant',
  error_description: "AADSTS50013: Assertion failed signature validation. [Reason - The key was not found., Thumbprint of key used by client: 'xxxxxxx'].\r\n" +
    'Trace ID: xxxxxxx\r\n' +
    'Correlation ID: xxxxxxx\r\n' +
    'Timestamp: 2021-12-09 22:29:34Z',
  error_codes: [ 50013 ],
  timestamp: '2021-12-09 22:29:34Z',
  trace_id: 'xxxxxxx',
  correlation_id: 'xxxxxxx',
  error_uri: 'https://login.microsoftonline.com/error?code=50013'
}
```

This is failing while the implicit flow is working and the popup scenario is able to retrieve the access token for MS Graph. Does this mean that Outlook Web is not supporting SSO? or is there a problem with the code or my specific settings?

I really appreciate any help you can provide.

**Comment by RuoyingLiang** [comment]
Thanks for reaching out. @davidchesnut, could you help to take a look?

**Comment by davidchesnut** [comment]
Hi @saaniaki, 

My first recommendation is to be sure that the sample works first (before you change it to work with Outlook.) Just to be sure registration and code is set up properly before making any changes.

Often errors are caused by missing a step in the registration process.
* I found a few stackoverflow answers indicating that this error is often a result of a poorly configured Application ID URI. So double-check in steps 8 and 9 of [Register the add-in with Azure AD v2.0 endpoint](https://docs.microsoft.com/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs#register-the-add-in-with-azure-ad-v20-endpoint) that you configured this correctly.
* Also be sure you added the Outlook on the web client ID (GUID) in step 15 of the same article.

I should point out that the Office platform team just focuses on providing these samples to help developers get started. We can help with anything specific to Office (such as the getAccessToken API, or dialog APIs.) However, once you start customizing them you'll be going deeper into the territory of the Microsoft identity platform. So if you are having trouble with the on behalf of flow, token related errors, app registration questions, and so on, a good place to reach out for help is at https://docs.microsoft.com/en-us/azure/active-directory/develop/developer-support-help-options

In the meantime, we are happy to try to help troubleshoot customizations, but it may take more time for us to research the issue.

Hope this helps,
David

**Comment by saaniaki** [comment]
Thank you @davidchesnut!

I can confirm that I have followed the documentation step by step and everything is set up correctly. I have double-checked steps 8, 9 and 15 and everything is as expected.

Regarding the customization, I have just modified the manifest.xml file to match the one that YO generates. so nothing special there. The sample is not working on MS Word Web and it returns 13007, not even being able to obtain the SSO token.

One thing I need to mention is that the `Office.auth` is not available on the Outlook Web, it is available on the Office Word Web. So I'm using `OfficeRuntime.auth` instead on the Outlook Web.

Please let me know what information I can provide to further debug this issue.

**Comment by saaniaki** [comment]
One thing I have found out is that this problem could be related to the fact that our application is SAML enabled. I have a problem saving the Application ID URI. When I set it to `api://localhost:port/app_GUID` the SAML integration stops working. When I go to the Enterprise Applications and correct the Identifier (Entity ID) of the SAML settings, then the Application ID URI will be set to the Identifier (Entity ID)! I have no idea how to set these values to two different things.

**Comment by saaniaki** [comment]
Okay, so something must be wrong with the settings as you said but I'm to find it. This is how I confirm this assumption:

1- I hit the `https://login.microsoftonline.com/90426024-bc1a-4e0d-92da-88bf48667326/oauth2/v2.0/token` and obtain an access token.
2- I pass it to the `https://login.microsoftonline.com/90426024-bc1a-4e0d-92da-88bf48667326/oauth2/v2.0/token` and I get the same error response.

This confirms the code is doing what is it supposed to do and passes the correct access code to the token endpoint.

**Comment by davidchesnut** [comment]
Hi @saaniaki, 

I did repro the problem where the sample won't run in Word online. For some reason it looks like the tsconfig files were somehow causing the issue. I believe they were added to make the projects backwards compatible with IE11, however since the promise polyfills are missing, I'm not sure it would have worked completely. To simplify the samples I removed all the tsconfig parts. This also makes it simpler to debug when running. And this works in Word, Excel, PowerPoint from my own testing.

It would be great if you could take a look at #226 and let me know if that gets the sample working in Word for you.

As for SAML, I don't know. These samples are designed for the OAuth flow. You'd need to follow up with the Microsoft identity platform team for more info about working with SAML. (https://docs.microsoft.com/en-us/azure/active-directory/develop/developer-support-help-options)

Thanks,
David

**Comment by saaniaki** [comment]
Hi @davidchesnut,

Thank you for your follow-up. I have got in touch with MS Support and this is a limitation of Azure when combining OAuth with SAML. To overcome the issue, I had to create two separate app registries, one which works with SAML and the other one that handles the OBO flow. It would have been nice if this information was available on the documentation.

Anyhow, I can confirm that the code has no problems and I got it to work on Outlook Web too. We can close this ticket now :)

Thank you again,
Ali
