### ISSUE TITLE
A template for an Excel Custom Functions project with a React Taskpane

### ISSUE THREAD

**Issue by toinetoine** [OfficeDev/Office-Add-in-samples#242]
Could we get a template for creating an Excel Custom Functions project with a **React Taskpane**. There is no yeoman office generator option for this:

https://github.com/OfficeDev/generator-office#--projecttype

Attempts I have made both:

  1. To go from a React Taskpane project to adding Custom functions 
  `yo office --projectType react --host excel --ts true`

  2. And vice versa: from a Custom Functions project to adding a React Taskpane
  `yo office --projectType excel-functions --host excel --ts true`

have **both** failed.

**Comment by AlexJerabek** [comment]
Hi @toinetoine,

Thanks for this request. If you could, please request this additional template from the [yo office repo](https://github.com/OfficeDev/generator-office). There, members of the Office Platform Developer Experience can work with you to make the template that fulfills your scenario.

In the meantime, have you tried using the React Taskpane option as a starting point? You can add the parts of a Custom Functions add-in to that. To make that work, you'll need to:

1. Add the following "devDependencies" to your **package.json**: `"@types/custom-functions-runtime": "^1.6.0"`, `"custom-functions-metadata-plugin": "^1.2.5"`
2. Add **src/functions/functions.ts** to your React project. I used the same functions.ts file from that yo office generates for the Excel Custom Functions project, which you can copy from [here](https://gist.github.com/AlexJerabek/d9dde35f55b7a3271c1c04fe15f681af).
3. Add the custom functions parts to the **manifest.xml**. [Here's my manifest](https://gist.github.com/AlexJerabek/04925ca5f07bf76a117fd0bfae45fee6). The key parts are listed out [here](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview#manifest-file), but feel free just to copy and paste mine.
4. Edit your **webpack.config.js** file. The full steps for converting a project to the shared runtime (which makes developing custom functions projects easier) are [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime#configure-the-manifest) (you can ignore the stuff under "Test your Office Add-in changes"). However, since you're not starting from the yo office custom functions project, you'll need the handful of plugins that adds. [Here's my version](https://gist.github.com/AlexJerabek/09f6257ff9e85136fdf046fa285ffcbe) for convenience. 
5. [Clear the Office cache](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache). Custom functions rely heavily on cached information, so clearing the cache regularly during development is important.
6. Run `npm install`, `npm run build`, and `npm start` when you're ready to build and test your add-in.

Please let me know if this works out for you. Hopefully, I didn't miss a step.

**Comment by toinetoine** [comment]
Thank you for replying so soon @AlexJerabek! 

I did go from react -> custom functions previously but I restarted and followed the steps you outlined directly. Running the result has the functions working 🎉 but the taskpane is blank.

![result_running](https://user-images.githubusercontent.com/1865818/149412736-4ef21e81-ec14-4984-ac6e-852c215e1555.png)

I pushed the project (with the manifest and webpack config you sent me) [here](https://github.com/toinetoine/ExcelJSReactTaskpaneWithCustomFunctionsForAlex). I made sure the linked repo works (I re-cloned it to another location, cleared excel cache, and ran `npm install`, `npm run build`, `npm start` from the base folder). 

Is there anyway you could share the project you have with the working react taskpane and custom functions or try the one I pushed?

I have been clearing my caches (`C:\Users\toinetoine\AppData\Local\Microsoft\Office\16.0\Wef` & `C:\Users\toinetoine\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC\#!123\INetCache`) religiously between runs.

---

Also you mentioned that converting to shared runtime would make it easier, I did that before adding the functions but doesn't custom functions require:
```
<Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>
```
(thereby overriding): 
```
<Requirements>
  <Sets DefaultMinVersion="1.1">
    <Set Name="SharedRuntime" MinVersion="1.1"/>
  </Sets>
</Requirements>
```

Thanks.

**Comment by AlexJerabek** [comment]
Here's a copy of my project (minus the **dist** and **node_modules** folders. Try that out on your machine and see if it works. Otherwise, I can take a look at your project tomorrow.

[CFReact.zip](https://github.com/OfficeDev/Office-Add-in-samples/files/7866726/CFReact.zip)

**Comment by toinetoine** [comment]
Thanks @AlexJerabek! Just ran your project and works. Thank you for your help!
