### ISSUE TITLE
word-blazor-add-in: How to create the project from scratch

### ISSUE THREAD

**Issue by Martin-Andersen** [OfficeDev/Office-Add-in-samples#319]
Please delete this. I found the solution in the property pane

![image](https://user-images.githubusercontent.com/203121/170820436-25d018df-29c0-4c50-b33c-36c932eec34f.png)

https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/word-blazor-add-in

First thanks to Maarten van Stam for creating the example and showing how to use Blazor with office.js.

I am trying to create the example from scratch. 

1.  First I created a new office web add-in for excel.
2. Then I deleted the web projekt so that only the manifest project is left.
3. Then I added a stand-alone Blazor WASM site.

Now I need to link the Manifest and Blazor project together so I can hit F5 and debug the project.
But I can't figure out what kind of magic that's tell the Manifest project where there Blazor project are located.

I am getting the following error:

`
Error Invalid manifest: the ~remoteAppUrl token can only be used when the add-in project has an associated web project.	excel-blazor-sideloader	C:\Users\maa\source\repos\excel-blazor-add-in\excel-blazor-sideloader\excel-blazor-sideloaderManifest\excel-blazor-sideloader.xml	
`

The missing link! How do I join the two project

**Comment by aafvstam** [comment]
Saw your edit (changing the web project in the Properties). This indeed is the way to go to swap out the existing project with a new project.

Don't forget to change the default TaskPane URL if that is named differently in your new project otherwise the Add-in can't be found:
`<bt:Url id="Contoso.Taskpane.Url" DefaultValue="~remoteAppUrl/" />`
