### ISSUE TITLE
Having issue while running the sample

### ISSUE THREAD

**Issue by rak-dev** [OfficeDev/Office-Add-in-samples#515]
Hi, 
I followed all the steps given on this [link](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs) but after accessing the application on [localhost](https://localhost:3000/home/index) and when i click on Get OneDrive FileNames i am getting following error

```
SSO failed. Trying fallback auth.
---Cannot get access token. Both SSO and fallback auth failed. TypeError: Cannot read properties of undefined (reading 'displayDialogAsync')
---
```
![sso error](https://user-images.githubusercontent.com/64973298/232685726-8c2c779a-8993-4d82-8fa5-7c583dba0e65.png)

Please help, as I have no clue what I am doing wrong here.

**Comment by AlexJerabek** [comment]
Hi @rak-dev,

Sorry to hear you're having issues. To confirm, are you starting with the [Office Add-in that supports Single Sign-on to Office, the Add-in, and Microsoft Graph](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO) sample? Are you seeing this issue in the "Begin" or "Complete" version?

Let me assign @davidchesnut to follow up after we get your responses.

**Comment by davidchesnut** [comment]
Hi @rak-dev,

Thanks for including the detailed error output. It's odd because Office.context.ui.displayDialogAsync should just be there from Office JS.

Can you try running the sample in Office on the web, and then when you see the issue, open the developer tools to inspect the add-in source code. See if the console window is reporting any errors with loading the JavaScript. 

You can also debug in Office on Windows by right-clicking the add-in's task pane and choosing Inspect. 

Thanks!
David

**Comment by rak-dev** [comment]
thanks for the quick tips its resolved now. So closing this issue
