### ISSUE TITLE
Outlook Web Add-in Blazor Example for OnMessageSend Event

### ISSUE THREAD

**Issue by CorithMalin82** [OfficeDev/Office-Add-in-samples#578]
**Question**
(asked on [stackoverflow](https://stackoverflow.com/questions/76802400/outlook-web-add-in-blazor-and-onmessagesend?noredirect=1#comment135482209_76802400), but was directed to ask here)

I've seen and followed the sample for creating an Outlook Web Add-in using Blazor for a TaskPane add-in. I've tried adapting it to work with the OnMessageSend event of web add-ins. I've hit a wall though trying to get it to load. From what I can tell, the main difference between a TaskPane and OnMessageSend add-in that stops this from working is that a TaskPane add-in requires an HTML endpoint to be invoked/called and the OnMessageSend add-in requires a JavaScript function. But there doesn't seem to be a way with a Blazor app to make the entry point a javascript function (it has to be a web page being loaded)?

Am I missing something obvious that would enable a web add-in targeting the OnMessageSend feature to use Blazor or WASM?

Thanks!

**Comment by davidchesnut** [comment]
Hi @CorithMalin82,

Unfortunately, I don't think this scenario will work.  When Outlook on Windows launches your code to handle an event it uses a plain JavaScript engine. There's no UI or browser runtime, which likely Blazor WebAssembly would expect. 

It's possible it might work in Outlook on the browser. In that case Outlook will use the browser to run your event code. Have you tried that scenario?

@aafvstam do you have any ideas here?

Thanks!
David

**Comment by CorithMalin82** [comment]
Hi David,
  We were testing in the browser and on Windows Desktop with Outlook 365.  Both would work with a TaskPane but neither would work when trying to use the `OnMessageSend` feature.  I suspect you're right on about the UI or browser runtime, as the issue we've encountered is an inability to get the blazor app to load because it seems it's never being hit.

Do you know if Blazor apps for the `OnMessageSend` feature are in the works?  It would enable my company to drastically speed up the processing of our web add-in as right now we end up having to do the processing remotely using the GraphAPI instead of locally via JavaScript.  It would also save us compute resources as we could do our processing on the client's computer instead of in our clouse services.

Thanks for your thoughts and comments.

**Comment by CorithMalin82** [comment]
@davidchesnut - Just wanted to check in with you to see if the Blazor team ever got back to your question.  No worries if they didn't as I appreciate that you reached out to them. :)

**Comment by davidchesnut** [comment]
Hi @CorithMalin82, yes I checked into this more and discovered that the JavaScript engine that runs your event code doesn't support loading JS libraries. There's no way to provide an HTML Script tag to point to any libraries. So right now there isn't a way to load Blazor with event code in Outlook.

If you want to request this feature, please go to our [feature request site for Microsoft 365](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). You can create a request with more details there. One thing we are curious about, since there is no UI in events, is are you just wanting Blazor to run c# code, or is there more to your scenario? We'd like to know more. 

Thanks!
David
