### ISSUE TITLE
No Excel ContentApp sample found which works with Microsoft 365 integrated app publishing

### ISSUE THREAD

**Issue by suppenburger** [OfficeDev/Office-Add-in-samples#614]
**URL of sample**
https://github.com/OfficeDev/Office-Apps/blob/master/PeopleGraph/PeopleGraph/PeopleGraphManifest/PeopleGraph.xml

**Describe the bug**
One of the ways described by Microsoft to publish an Excel add-in is Integrated Apps. https://learn.microsoft.com/en-us/microsoft-365/admin/manage/test-and-deploy-microsoft-365-apps?view=o365-worldwide. However is trying to publish a ContentApp sample from this repository (e.g. PeopleGraph) the validation fails ("Error=Invalid manifest file").

![IntegratedApps](https://github.com/OfficeDev/Office-Add-in-samples/assets/3450963/88b2c00f-c693-4b7f-a964-03af459bfc01)

**To Reproduce**

1. Download file PeopleGraph.xml
2. Open Microsoft 365 admin center
3. Select Settings > Integrated app on the left navigation
4. Click "Upload custom apps"
5. Pick App type "Office Add-in"
6. Chose PeopleGraph.xml for "Upload manifest file (.xml) from device
7. Error message "Invalid manifest file" appears

**Expected behavior**
As the manifest file is downloaded from the official samples repo I expect that no validation error is shown. Also I would expect a working ContentApp sample is the Office-Add-in-samples repository.

**Environment**
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Operating System: Mac
- Browser (if using Office Online): Microsoft Edge Version 117.0.2045.55 (Official build) (arm64)

**Comment by davidchesnut** [comment]
Hi @suppenburger,

That manifest won't work because it is using the "~remoteAppUrl" placeholder from Visual Studio. When you build the solution, Visual Studio will build a new version of the XML with the completed URL at PeopleGraph\PeopleGraph\bin\Debug\OfficeAppManifests. That's the one you want to load.

BTW: That sample is really old and I'll take a look at it to see if we want to maintain it or archive it. Just be aware as there could be better approaches to some of its features as Office.js has improved over the years.

Hope this helps,
David

**Comment by suppenburger** [comment]
@davidchesnut there was 2nd Url placeholder for "IconUrl" property. But this still did not solve my issue. 

```
    <Capabilities>
        <Capability Name="Workbook" />
    </Capabilities>
```
This seems not be valid xml anymore. 

Had to replace it with 

```
  <Hosts>
    <Host Name="Workbook" />
  </Hosts>
```
Therefore I kindly suggest to re-open the issue and add an updated sample which includes a valid manifest file working with M365 integrated apps.
