### ISSUE TITLE
 Uncaught (in promise): InvalidRibbonDefinition: InvalidRibbonDefinition RichApi.Error: InvalidRibbonDefinition

### ISSUE THREAD

**Issue by AbhishekKatariya9** [OfficeDev/Office-Add-in-samples#631]
**Question**

I am trying to disable ribbon using office js library. while running below code I am getting this error 
ERROR:  Uncaught (in promise): InvalidRibbonDefinition: InvalidRibbonDefinition
RichApi.Error: InvalidRibbonDefinition

Code: `Office.ribbon.requestUpdate({
      tabs: [
        {
          id: 'TabCustom',
          groups: [
            {
              id: 'Tab.Group2',
              controls: [
                {
                  id: 'Dataverse',
                  enabled: false,
                },
              ],
            },
          ],
        },
      ],
    });`

**Comment by alison-mk** [comment]
Hi @AbhishekKatariya9, thank you for submitting. We use Github issues to report bugs with the samples in this repository, and it looks like your question uses code that is not from one of the samples in this repository. 

For programming questions like this, we suggest you go to [Stack Overflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. Stack Overflow has an active community of developers that regularly provide feedback and guidance. 

Since this isn't a bug, I will close this issue. Let me know if you have any questions!

Alison
