### ISSUE TITLE
is there a equation support?

### ISSUE THREAD

**Issue by devmdeniz** [OfficeDev/Office-Add-in-samples#807]
**Question**
I am coding a project about formulas. I want to write the formulas in LaTeX format in my word plugin as in the equation feature. At first I tried to put $$ at the beginning, but then I realized that I had to translate it on my own by pressing the equations button, which is word's own feature. I couldn't find any information in the docs about converting it to an equation. How can I do this or when will it be available?

**Comment by AlexJerabek** [comment]
Hi @devmdeniz,

Thanks for reaching out. The Office JS APIs do not currently have support for the Word equation feature. I'd recommend that you submit a feature request to the [Microsoft 365 Developer Platform Tech Community](https://aka.ms/m365dev-suggestions).  There, we can gauge community need and interest in new features and prioritize them accordingly.

I'm going to close this issue, since there is nothing actionable to be done in the samples.
