### ISSUE TITLE
Word import template from local path

### ISSUE THREAD

**Issue by Hydro8** [OfficeDev/Office-Add-in-samples#899]
Hi

I would like to use the import template for Word but with a local file directly.
So instead of selecting file with the file input, I'll have a button and when I'll click, it'll load the file.

Is it possible ?

I tried to use new File but it doesn't work :

```
    // Gets the contents of the selected file.
async function getFileContents() {
//const myTemplate = document.getElementById("template-file");
const file = new File(["Trame"], "Trame.docx");
const reader = new FileReader();
reader.onload = (event) => {
    // Remove the metadata before the Base64-encoded string.
    const startIndex = reader.result.toString().indexOf("base64,");
    template = reader.result.toString().substring(startIndex + 7);

    // Import the template into the document.
    importTemplate();

    // Show the Update section.
    $("#imported-section").show();
};

// Read the file as a data URL so we can parse the Base64-encoded string.
reader.readAsDataURL(file);
}
```

Any ideas how to do the same thing without the selector ? My word document is currently in the same folder as taskpane.html but it can be on a network share.

Thanks for your help.

**Comment by ElizabethSamuel-MSFT** [comment]
@Hydro8 Thanks for your question. However, this is beyond the scope of Office JavaScript APIs since it pertains more to general file interactions in JavaScript/HTML.

For the most part, security-wise, it's usually not permitted for a browser to directly access the user's local machine. Because Office Add-ins run in a browser context regardless of the platform, they have many of the same restrictions in that sense.

Perhaps you can prepopulate the name of the file and certainly the type of the file, but I think it's likely that the user must select the file. If you have an absolute path for the file that the user can access, you could also display that location in the add-in UI so the user can copy-paste it into the file selector. The community on [Stack Overflow](https://stackoverflow.com/) or a similar forum may be able to provide you with a solution for your situation.

I'm going to close this issue and thank you for your interest in Office Add-ins.
